# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solver',
            name='slug',
            field=models.TextField(default='glucose', max_length=20),
            preserve_default=False,
        ),
    ]
